language: swift
osx_image: xcode10.1
xcode_sdk: iphonesimulator12.1
xcode_project: Twilio Message.xcodeproj
xcode_scheme: Twilio Message
xcode_destination: platform=iOS Simulator,OS=12.0,name=iPhone SE

#XCPretty version used doesn't currently work with Xcode10
before_install:
  - brew install carthage
  - carthage update --platform iOS
  - Scripts/updateInfoPlistUnitTest.sh
  - Scripts/updateInfoPlistUITest.sh

after_success:
  - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN
